### PR TITLE
Upgraded JS deps

### PR DESCRIPTION
**Pull request by rhysyngsun**
#### What are the relevant tickets?
Part of #379 

#### What's this PR do?
Updates JS deps (react, babel, webpack, etc) to support newer toolchains

#### How should this be manually tested?
App should compile and run without error

### CODE REVIEW

**Comment by noisecapella** [comment]
I'm seeing a webpack error:
Screenshot from 2020-04-15 15-56-36

**Comment by rhysyngsun** [comment]
@noisecapella did you rebuild your containers? sorry, should've mentioned that in my testing instructions

**Comment by noisecapella** [comment]
Yes, but I'm still seeing the error

**Comment by noisecapella** [comment]
Looks like there are some style differences. On master:
Screenshot from 2020-04-16 13-12-46

On this PR:
Screenshot from 2020-04-16 13-08-48

**Comment by rhysyngsun** [comment]
@noisecapella I fixed the styles to be more in line with the original, but didn't aim for pixel-perfect since it's not the most polished UI to begin with.

**Pull request merged**
