### PR TITLE
update product page instructors section design

### PR DESCRIPTION
**Pull request by umarmughal824**
#### What are the relevant tickets?
(Required)

#### What's this PR do?
Update Page Instruction Section CMS model and design

#### How should this be manually tested?
Create Instructors Section in the product page

#### Screenshots
**CMS MODEL**

screencapture-bc-odl-local-8099-cms-pages-13-edit-2020-05-22-16_47_36

**DESKTOP**

Screenshot 2020-05-22 at 16 52 16
Screenshot 2020-05-22 at 16 53 19
Screenshot 2020-05-22 at 17 11 35
Screenshot 2020-05-22 at 17 11 40

**Tablet**

Screenshot 2020-05-22 at 16 59 58
Screenshot 2020-05-22 at 17 00 14
Screenshot 2020-05-22 at 17 00 35
Screenshot 2020-05-22 at 17 00 47

**MOBILE**

Screenshot 2020-05-22 at 17 02 01
Screenshot 2020-05-22 at 17 02 11
Screenshot 2020-05-22 at 17 02 19
Screenshot 2020-05-22 at 17 02 30

**FULL PAGE SO FAR**

screencapture-bc-odl-local-8099-bootcamps-bootcamp-13-2020-05-22-17_17_41

### CODE REVIEW

**Comment by umarmughal824** [comment]
@pdpinch could you please review the attached screenshots.

**Comment by pdpinch** [comment]
FYI, I'm trying to find out what that "Framework" link is for. I don't understand it. 

Just a couple of comments:

1. I'm concerned that the "subhead" is too small of a box in the CMS. Can you make that a text area so the CMS user can see all the text at once? 
2. We don't need the circles anymore. The only navigation will the be the arrows
3. The arrow design is changed a bit:
image
4. In particular, don't places the arrows over the headshot images, even in mobile. 
5. In mobile, when the Sections text wraps below the heading instead of the right, the line on the left of the text should disappear.

**Comment by umarmughal824** [comment]
@pdpinch that "Framework" was given there on the invision design so that why I decided to use `rich text` rather than simple text field. But now addressing your feedback.
Framework mentioned in the images see that screenshot

Screenshot 2020-05-22 at 13 59 16

**Comment by umarmughal824** [comment]
@pdpinch I have updated the screenshots in the PR description, could you please review it?

**Pull request merged**
