### PR TITLE
Bootcamp certificates feature

### PR DESCRIPTION
**Pull request by HamzaIbnFarooq**
#### What are the relevant tickets?
https://github.com/mitodl/bootcamp-ecommerce/issues/1095

#### What's this PR do?
Adds Certificate feature

#### How should this be manually tested?
**Set environment:**
Set `FEATURE_ENABLE_CERTIFICATE_USER_VIEW` to `True` in `.env`.
Create a `User` and make sure its `Profile` and `Email Address` exists.

**Go to CMS:**
Create `Certificate Index Page` under `root/main-page` (make sure the slug is set to “certificate” for navigation)

Create `Signatory Index Page` under `root`
Add some `Signatories` under `Signatory Index Page`

Create `Bootcamp Index Page` (if not already)
Create a `Bootcamp-run Page` under `Bootcamp Index Page`
Create `Certificate Page` under that `Bootcamp-run Page`

While creating `Certificate Page` you will find a `Secondary Image` option, it can be used to add `Secondary Institue Logo`.

**Now go to Application:**
Enroll User in the bootcamp-run whose certificate you just created.

**Now go to Django shell:**
$ `docker-compose run --rm web bash`
$ `./manage.py manage_certificates --run <BOOTCAMPRUN ID or TITLE>  --generate-batch   # It will generate certificates for all the enrolled learners in that bootcamp-run`

**Now get back to Application  "/applications/“:**
`"View Certificate"` button will start showing, you can click on that link to view the certificate.

#### Types of Certificate Commands?
1) "./manage.py manage_certificates `--user <USER-ID>` `--run <BOOTCAMP-RUN-ID>` `--revoke`"  # To revoke certificates
2) "./manage.py manage_certificates `--user <USER-ID>` `--run <BOOTCAMP-RUN-ID>` `--unrevoke`"  # To unrevoke certificates
3) "./manage.py manage_certificates `--user <USER-ID>` `--run <BOOTCAMP-RUN-ID>` `--generate`"  # To generate certificates
4) "./manage.py manage_certificates `--run <BOOTCAMP-RUN-ID>` `--generate-batch`" # To generate certificates for everyone whose enrollment is active 

#### Screenshots (if appropriate)
Desktop:
image

Mobile:
image

Print:
image

#### What GIF best describes this PR or how it makes you feel?
(Optional)

### CODE REVIEW

**Comment by pdpinch** [comment]
Why are the signatures rendering with a checkerboard background? 

I think if that's fixed, or if it's not really an issue, we can go ahead and merge this so I can get it up on RC.

**Comment by HamzaIbnFarooq** [comment]
> Why are the signatures rendering with a checkerboard background? 
> 
> I think if that's fixed, or if it's not really an issue, we can go ahead and merge this so I can get it up on RC. 

That image has the checkerboard background, nothing to do with template rendering.

How would you like to get it merged, as a single commit or vice versa?

**Comment by pdpinch** [comment]
In this case, I'd prefer you preserve the individually commits. But it's not a big deal.

**Comment by HamzaIbnFarooq** [comment]
@pdpinch The branch is merged, you may proceed with RC deployment.

**Pull request merged**
