### PR TITLE
Feat: Allow users to specify bootcamp location in CMS

### PR DESCRIPTION
**Pull request by collinpreston**
Adds a migration to change the AdmissionsSection's bootcamp_format and bootcamp_format_details to be bootcamp_location and bootcamp_location_details respectively.  Updates the UI where these values are displayed to label them as "Location" as well as displaying the value in the ApplicationDashboardPage.

#### What are the relevant tickets?
https://github.mit.edu/bootcamps/bootcamps-issues/issues/18

#### What's this PR do?
Allows user's to specify a Location and Location Details through the bootcamp CMS editor.

#### How should this be manually tested?

- Follow the steps in the "Where should the reviewer start?" section of this PR.
- visit the bootcamp course page (http://bc.odl.local:8099/bootcamps/collin-bootcamp/) which can be easily accessed by clicking the "Iive" link in the CMS.
- Apply for a program and view the application through http://bc.odl.local:8099/applications/
- Verify that both pages correctly show and label the location field and details.

#### Where should the reviewer start?

- Once you have bootcamp up and running locally, perform the initial step of seeding it with data (https://github.com/mitodl/bootcamp-ecommerce#seed-data).
- Perform a `docker-compose run web ./manage.py migrate` to ensure that you have the database changes.
- Go to <bootcamp_base_url>/cms and login with your admin user.
- Create a bootcamp index page, a bootcamp page, and finally an admissions page through CMS.  The pages don't need to be completely filled out or require any specific data.  On the admissions page ensure that you see the BOOTCAMP LOCATION and BOOTCAMP LOCATION DETAILS fields.  Enter data into those fields.
Screen Shot 2022-11-09 at 15 03 51
Screen Shot 2022-11-09 at 15 03 41

#### Screenshots (if appropriate)
Screen Shot 2022-11-09 at 15 11 59
Screen Shot 2022-11-09 at 15 12 13

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
I've got some existing data already, tried to run `manage.py configure_cms` and got an `IntegrityError`, not sure if it's due to bad data on my end yet or not.

Also, I tried reverting the new migration (which is sometimes necessary if things go wrong) and was not able to:

```
 ERROR: column "bootcamp_format" contains null values
 ```

**Comment by collinpreston** [comment]
> I've got some existing data already, tried to run `manage.py configure_cms` and got an `IntegrityError`, not sure if it's due to bad data on my end yet or not.
> 
> Also, I tried reverting the new migration (which is sometimes necessary if things go wrong) and was not able to:
> 
> ```
>  ERROR: column "bootcamp_format" contains null values
> ```

I see the same thing after reverting the migration locally and then trying to reapply it.  I'll have to come back to this later tonight.

**Review by mbertrand — APPROVED** [review]
Started with a fresh database this time.  Functionality seems to work fine, reverting the migration worked too, and also `configure_cms` command.  Code looks good!

**Comment by cachob** [comment]
As soon as we deem this good to go, let's go ahead and deploy

**Pull request merged**
