### PR TITLE
Upgrade Deps, immer to 8.0.1 & pysaml2 to 6.5.1

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### What are the relevant tickets?
fixes https://github.com/mitodl/bootcamp-ecommerce/issues/1152
fixes https://github.com/mitodl/bootcamp-ecommerce/issues/1153

#### What's this PR do?
- Upgrades `immer` to 8.0.1
- Upgrades `pysaml2` to 6.5.1

#### How should this be manually tested?
Checking that tests are passing, as we a majorly relying on coverage for these dependency upgrades.

### CODE REVIEW

**Comment by pdpinch** [comment]
@umarmughal824 can you review?

**Comment by umarmughal824** [comment]
@arslanashraf7 please update your relevant ticket description section like `fixes #<ticket_number>` so that it could close the issue on merging the PR.

**Comment by arslanashraf7** [comment]
> @arslanashraf7 please update your relevant ticket description section like `fixes #<ticket_number>` so that it could close the issue on merging the PR.

@umarmughal824 I intentionally started the practice of not writing the `fixed/closes` with PR as per the discussion on slack about when an issue is to be considered `Done`, and as per that the issue is `Done` when its deployed on production & available to end user. If it needs more clarification or you have a suggestion otherwise please let me know.

**Comment by umarmughal824** [comment]
> > @arslanashraf7 please update your relevant ticket description section like `fixes #<ticket_number>` so that it could close the issue on merging the PR.
> 
> @umarmughal824 I intentionally started the practice of not writing the `fixed/closes` with PR as per the discussion on slack about when an issue is to be considered `Done`, and as per that the issue is `Done` when its deployed on production & available to end user. If it needs more clarification or you have a suggestion otherwise please let me know.



> > @arslanashraf7 please update your relevant ticket description section like `fixes #<ticket_number>` so that it could close the issue on merging the PR.
> 
> @umarmughal824 I intentionally started the practice of not writing the `fixed/closes` with PR as per the discussion on slack about when an issue is to be considered `Done`, and as per that the issue is `Done` when its deployed on production & available to end user. If it needs more clarification or you have a suggestion otherwise please let me know.

No, I don't see that approach suggested by MIT. Even I was forced to do so even in my home page redesign PR by Peter just got merged yesterday.

**Review by umarmughal824 — APPROVED** [review]
Just a minor suggestion
Add `fixes #<ticket_number>` in your PR description relevant tickets section.

**Comment by arslanashraf7** [comment]
> Just a minor suggestion
> Add `fixes #<ticket_number>` in your PR description relevant tickets section.

Updated, Thanks for the review!

**Comment by umarmughal824** [comment]
@arslanashraf7 this suggestion lets you see what PR fixed it in the future to see the changes. This is how it does look like 
Screenshot 2021-02-10 at 17 54 56

**Pull request merged**
