### PR TITLE
feat: add early bird deadline

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### What are the relevant tickets?
- https://github.com/mitodl/hq/issues/2941
- https://github.com/mitodl/hq/issues/2943

#### What's this PR do?
- Removes the deadline from the payment section in a bootcamp application
- Adds early bird deadline in a bootcamp application in the video interview section of the application

#### How should this be manually tested?

- Enroll in any bootcamp
- Use `set_application_state` command to set the user's application state if necessary
- Check that there is no deadline shown on the payment section of the application
- Set a date for the early bird deadline in bootcamp run
- Check that you see `Early Bird Deadline` in the `Video Interview section` of the Bootcamp application
- Now set the application state to `Video Interview completed`, You should not see an early bird deadline now

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)

**When early bird deadline is set**
image

---

**When early bird deadline is set**
image

---

**When the status is completed** (No deadline will be shown even set)
image

### CODE REVIEW

**Review by asadali145 — APPROVED** [review]
LGTM!

**Comment by arslanashraf7** [comment]
@cachob Can you take a look at the screenshots when you get back? Let me know if they look good to you.

**Comment by arslanashraf7** [comment]
@cachob I'm going to merge this, If there will be other design changes requested in this I'll do them through a followup PR.

**Comment by cachob** [comment]
This looks good

**Pull request merged**
