### PR TITLE
Change references to Apply/Admissions to text entry fields in the CMS

### LINKED ISSUE #1303: Change references to Apply/Admissions to text entry fields in the CMS
As a user who is enrolling in a Bootcamp that doesn't require an application, I want to be clear that I am not required to fulfill any application steps to be able to take part in the bootcamp.

#### Designs and Mockups

There are three references to Apply / Admissions that need to be changeable. The mockup below shows how they could be customized.
image

#### Acceptance Criteria:

- [x] Create a new text entry field in the `Admissions Section` child page called `How to title` to replace the the [How to apply](https://github.com/mitodl/bootcamp-ecommerce/blob/4aca88c3e61af6f7c1fceb12df19723d8a8bcb9f/cms/templates/partials/admissions-section.html#L11) section heading
- [x] Create a new text entry field in the `Admissions Section` child page called `How to link` to replace the the [Admissions](https://github.com/mitodl/bootcamp-ecommerce/blob/4aca88c3e61af6f7c1fceb12df19723d8a8bcb9f/cms/templates/partials/admissions-section.html#L12) link text. (It will continue to link to the same URL)
- [x] Create a new text entry field in the `Admissions Section` child page called `Apply button` to replace the the [Apply Now](https://github.com/mitodl/bootcamp-ecommerce/blob/4aca88c3e61af6f7c1fceb12df19723d8a8bcb9f/cms/templates/partials/admissions-section.html#L24) text on the button.
- [x] They can be placed between `Admissions image` and `Notes` on the CMS page: 
Screen Shot 2021-10-29 at 3 04 54 PM

### PR DESCRIPTION
**Pull request by umarmughal824**
#### What are the relevant tickets?
fixes #1303

#### What's this PR do?
Change references to Apply/Admissions to text entry fields in the CMS

#### How should this be manually tested?
Just change the new fields text and verify it on the product page

#### Screenshots (if appropriate)

Screenshot 2021-11-08 at 18 36 45

### CODE REVIEW

**Comment by umarmughal824** [comment]
@briangrossman could you please review the attached screenshot in the PR description?

**Comment by briangrossman** [comment]
@umarmughal824 These look great. 

Very minor, but can you change `APPLY NOW BTN TEXT` to `APPLY NOW BUTTON TEXT` for the name of the button text field?

**Comment by umarmughal824** [comment]
@briangrossman this is how it looks like

Screenshot 2021-11-09 at 13 01 55

**Review by asadiqbal08 — APPROVED** [review]
👍

**Comment by briangrossman** [comment]
@umarmughal824 👍  - Thank you!

**Comment by briangrossman** [comment]
@umarmughal824 - Just tested on RC. It works great!

**Pull request merged**
