### PR TITLE
Update hubspot contact sync code

### LINKED ISSUE #402: Sync Learner Profile with Hubspot
As a marketing manager, I'd like to have all user profile data available to me in Hubspot, so I can segment my communications. 

As a bootcamp admin, I'd like to have all user profile data available in Hubspot so I can nurture applicants through application and payment.

┆Attachments: <a href="https://github.com/mitodl/bootcamp-ecommerce/pull/459">bootcamp-ecommerce #459 Update hubspot contact sync code</a>

### PR DESCRIPTION
**Pull request by mbertrand**
#### What are the relevant tickets?
Closes #402

#### What's this PR do?
- Removes the `HubspotContactSerializer` which had smapply-specific code
- Uses `profiles.UserProfileSerializer` for syncing contacts instead (like xpro)
- Updates `configure_hubspot_bridge` management command with new fields

#### How should this be manually tested?
- Run `manage.py configure_hubspot_bridge`
- Go to `/profile/edit` (after logging in) and edit your profile.  Enter something for all fields.
- Log in to hubspot and search contacts for the above user.  The changes should be reflected there.

### CODE REVIEW

**Comment by mbertrand** [comment]
You shouldn't have to, the celery task should run after submitting the profile form.  If not, might be worth checking if any tasks are running at all, or if the task did run but threw an error.

**Comment by annagav** [comment]
I am getting this error:
```celery_1  |   File "/src/smapply/tasks.py", line 30, in sync_all_users
celery_1  |     sync_bulk_with_hubspot(profiles_to_sync, make_contact_sync_message, "CONTACT", task_cache=task_cache)
celery_1  |   File "/src/hubspot/tasks.py", line 137, in sync_bulk_with_hubspot
celery_1  |     make_object_sync_message(obj.id, **kwargs)[0] for obj in objects
celery_1  |   File "/src/hubspot/tasks.py", line 137, in <listcomp>
celery_1  |     make_object_sync_message(obj.id, **kwargs)[0] for obj in objects
celery_1  | celery.beat.SchedulingError: Couldn't apply scheduled task sync-new-users-from-smapply: make_contact_sync_message() got an unexpected keyword argument 'task_cache'```

**Comment by mbertrand** [comment]
@annagav it should be fixed now

**Comment by annagav** [comment]
I filled out all my profile fields and I am trying to sync user with `sync_contact_with_hubspot`. I get 204 response, but I do not see any updated fields in hubspot. I also don't see any sync errors.

**Comment by mbertrand** [comment]
@annagav it looks like this one is yours? https://app.hubspot.com/contacts/6431386/contact/335651/properties?eschref=%2Fcontacts%2F6431386%2Fcontact%2F335651%2F&esclabel=Back

**Comment by annagav** [comment]
Yes it is. I did fill out all the Profile fields for the user, but I don't see them in hubspot.

**Comment by mbertrand** [comment]
I think there might actually be an issue with switching from using profile.id to user.id when creating the integration object id, I am going to try to sort that out.

**Comment by mbertrand** [comment]
@annagav I changed it back to using `profile.id` for the hubspot integratorObjectId, otherwise there was a chance the wrong contact would be updated. Sorry for the confusion.

**Comment by annagav** [comment]
@mbertrand I am able to see the profile fields updated in hubspot. Code looks good 👍

**Pull request merged**
